name: Ejercicio2

on: push

jobs:
  tareas:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      
    steps:
      - name: Run code analysis
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
